---
name: 'Cloudflare Workers Cleanup'
description: 'Clean up and delete Cloudflare Workers based on patterns'
author: 'harunonsystem'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  worker-prefix:
    description: 'Worker prefix (e.g., "myapp-pr-" or "example-")'
    required: false

  worker-numbers:
    description: 'Numbers to delete (e.g., "1,2,3"). Used with worker-prefix to generate full worker names'
    required: false

  worker-names:
    description: 'Full names (optional, overrides prefix+numbers) (comma-separated)'
    required: false

  cloudflare-api-token:
    description: 'Cloudflare API Token'
    required: true

  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true

  dry-run:
    description: 'List workers to delete without actually deleting them'
    required: false
    default: 'true'

  exclude:
    description: 'Comma-separated list of worker names or patterns to exclude from deletion. Supports exact names (e.g., "myapp-dev,myapp-stg") and glob patterns (e.g., "*-develop,*-staging,*-production"). Excluded workers will never be deleted even if they match worker-pattern.'
    required: false
    default: ''

outputs:
  deleted-workers:
    description: 'List of deleted worker names (JSON array)'

  deleted-count:
    description: 'Number of workers deleted'

  skipped-workers:
    description: 'List of workers that were skipped (JSON array)'

  dry-run-results:
    description: 'Workers that would be deleted in dry run mode (JSON array)'

runs:
  using: 'node20'
  main: '../dist/cleanup/index.js'
