name: 'Cloudflare Workers Cleanup'
description: 'Clean up and delete Cloudflare Workers based on patterns or specific names'
author: 'harunonsystem'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  worker-pattern:
    description: 'Pattern for workers to delete (e.g., "project-pr-*", supports wildcards)'
    required: false

  worker-names:
    description: 'Specific worker names to delete (comma-separated)'
    required: false

  api-token:
    description: 'Cloudflare API Token'
    required: true

  account-id:
    description: 'Cloudflare Account ID'
    required: true

  dry-run:
    description: 'Only list workers that would be deleted without actually deleting them'
    required: false
    default: 'false'

  max-age-days:
    description: 'Only delete workers older than this many days'
    required: false

  exclude-pattern:
    description: 'Pattern for workers to exclude from deletion'
    required: false

  confirm-deletion:
    description: 'Require explicit confirmation for deletion (set to "yes" to proceed)'
    required: false
    default: 'yes'

outputs:
  deleted-workers:
    description: 'List of deleted worker names (JSON array)'

  deleted-count:
    description: 'Number of workers deleted'

  skipped-workers:
    description: 'List of workers that were skipped (JSON array)'

  dry-run-results:
    description: 'Workers that would be deleted in dry run mode (JSON array)'

runs:
  using: 'node20'
  main: '../dist/cleanup/index.js'
