name: 'Workers Cleanup'
description: 'Delete Cloudflare Workers with flexible cleanup modes'
author: 'harunonsystem'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API Token'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true

  # Cleanup mode
  cleanup-mode:
    description: 'Cleanup mode: pr-linked, manual, batch, batch-by-age'
    required: true

  # PR-linked mode options
  pr-number:
    description: 'PR number for PR-linked mode'
    required: false
  worker-name-prefix:
    description: 'Worker name prefix (e.g., "preview")'
    required: false
    default: 'preview'

  # Manual mode options
  worker-names:
    description: 'Comma-separated worker names to delete (manual mode)'
    required: false

  # Batch mode options
  batch-pattern:
    description: 'Worker name pattern for batch deletion (e.g., "preview-*")'
    required: false
  exclude-workers:
    description: 'Comma-separated worker names to exclude from batch deletion'
    required: false

  # Batch-by-age mode options
  max-age-days:
    description: 'Delete workers older than N days (batch-by-age mode)'
    required: false

  # Safety options
  dry-run:
    description: 'Dry run mode (list workers but do not delete)'
    required: false
    default: 'false'

outputs:
  deleted-workers:
    description: 'JSON array of deleted worker names'

  deleted-count:
    description: 'Number of deleted workers'

  skipped-count:
    description: 'Number of skipped workers'

runs:
  using: 'node20'
  main: '../dist/cleanup/index.js'
