name: Advanced Cleanup Workers (Using GitHub Secrets)

on:
  pull_request:
    types: [closed]
  schedule:
    # Run cleanup daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual deletion)'
        required: false
        default: 'true'
        type: boolean
      max_age_days:
        description: 'Maximum age in days for workers to keep'
        required: false
        default: '7'
        type: string
      emergency_cleanup:
        description: 'Emergency cleanup - remove ALL preview workers'
        required: false
        default: 'false'
        type: boolean
      exclude_patterns:
        description: 'Comma-separated patterns to exclude (e.g., "prod*,staging*")'
        required: false
        default: 'myapp-prod*,myapp-staging*'
        type: string
      custom_worker_pattern:
        description: 'Custom worker pattern to cleanup (overrides default)'
        required: false
        type: string

permissions:
  contents: read

jobs:
  cleanup-pr-workers:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event.action == 'closed' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup closed PR worker
        if: github.event.action == 'closed'
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-names: 'myapp-pr-${{ github.event.pull_request.number }}'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: false
          confirm-deletion: 'yes'

      - name: Emergency cleanup (all preview workers)
        if: github.event.inputs.emergency_cleanup == 'true'
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-pattern: ${{ github.event.inputs.custom_worker_pattern || 'myapp-pr-*' }}
          exclude-pattern: ${{ github.event.inputs.exclude_patterns }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: ${{ github.event.inputs.dry_run == 'true' }}
          confirm-deletion: ${{ github.event.inputs.dry_run == 'false' && 'yes' || 'no' }}

      - name: Cleanup old preview workers (manual/scheduled)
        if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.event.inputs.emergency_cleanup != 'true'
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-pattern: ${{ github.event.inputs.custom_worker_pattern || 'myapp-pr-*' }}
          exclude-pattern: ${{ github.event.inputs.exclude_patterns }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          max-age-days: ${{ github.event.inputs.max_age_days || '7' }}
          dry-run: ${{ github.event.inputs.dry_run == 'true' || github.event_name == 'schedule' }}
          confirm-deletion: ${{ github.event.inputs.dry_run == 'false' && 'yes' || 'no' }}

  cleanup-orphaned-workers:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.emergency_cleanup != 'true')
    needs: cleanup-pr-workers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find and cleanup orphaned workers
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-pattern: 'myapp-*'
          exclude-pattern: ${{ github.event.inputs.exclude_patterns || 'myapp-prod*,myapp-staging*' }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          max-age-days: '14'
          dry-run: ${{ github.event.inputs.dry_run == 'true' || github.event_name == 'schedule' }}
          confirm-deletion: ${{ github.event.inputs.dry_run == 'false' && 'yes' || 'no' }}

  audit-and-report:
    runs-on: ubuntu-latest
    environment: preview
    if: always() && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    needs: [cleanup-pr-workers, cleanup-orphaned-workers]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit remaining workers (dry run)
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-pattern: 'myapp-*'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: true

      - name: Create comprehensive cleanup summary
        run: |
          echo "## ðŸ§¹ Advanced Worker Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "**Configuration:** Advanced options enabled" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ github.event.action }}" == "closed" ]; then
            echo "### ðŸŽ¯ PR Cleanup" >> $GITHUB_STEP_SUMMARY
            echo "**Action:** Cleaned up PR #${{ github.event.pull_request.number }} worker" >> $GITHUB_STEP_SUMMARY
            echo "**Worker:** myapp-pr-${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ github.event.inputs.emergency_cleanup }}" == "true" ]; then
            echo "### ðŸš¨ Emergency Cleanup" >> $GITHUB_STEP_SUMMARY
            echo "**Pattern:** ${{ github.event.inputs.custom_worker_pattern || 'myapp-pr-*' }}" >> $GITHUB_STEP_SUMMARY
            echo "**Excluded:** ${{ github.event.inputs.exclude_patterns }}" >> $GITHUB_STEP_SUMMARY
            echo "**Warning:** This was an emergency cleanup operation" >> $GITHUB_STEP_SUMMARY
          else
            echo "### â° Scheduled/Manual Cleanup" >> $GITHUB_STEP_SUMMARY
            echo "**Pattern:** ${{ github.event.inputs.custom_worker_pattern || 'myapp-pr-*' }}" >> $GITHUB_STEP_SUMMARY
            echo "**Max Age:** ${{ github.event.inputs.max_age_days || '7' }} days" >> $GITHUB_STEP_SUMMARY
            echo "**Dry Run:** ${{ github.event.inputs.dry_run || 'true' }}" >> $GITHUB_STEP_SUMMARY
            echo "**Excluded:** ${{ github.event.inputs.exclude_patterns || 'myapp-prod*,myapp-staging*' }}" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ”§ Advanced Features Used" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… Custom worker patterns support" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… Flexible exclude patterns" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… Emergency cleanup mode" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… Orphaned workers detection" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… Comprehensive audit trail" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… Multi-job workflow coordination" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ“Š Job Status" >> $GITHUB_STEP_SUMMARY
          echo "**PR Workers:** ${{ needs.cleanup-pr-workers.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Orphaned Workers:** ${{ needs.cleanup-orphaned-workers.result }}" >> $GITHUB_STEP_SUMMARY
