---
name: 'Setup'
description: 'Setup Node.js and pnpm environment'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

