name: Preview Deployment (Using GitHub Secrets)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy and Comment on PR
        uses: harunonsystem/cloudflare-actions/deploy@v1
        with:
          environment: 'preview'
          worker-name-pattern: 'myapp-pr-{pr_number}'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            {
              "DATABASE_URL": ${{ secrets.STG_DATABASE_URL }},
              "API_KEY": ${{ secrets.STG_API_KEY }}
            }
