name: 'Deployment Comments'
description: 'Post deployment results as Pull Request comments'
author: 'harunonsystem'

branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  deployment-url:
    description: 'Deployed worker URL'
    required: true

  deployment-status:
    description: 'Deployment status (success/failure)'
    required: false
    default: 'success'

  worker-name:
    description: 'Deployed worker name'
    required: false

  github-token:
    description: 'GitHub token for posting comments'
    required: true
    default: ${{ github.token }}

  custom-message:
    description: 'Custom message to include in comment'
    required: false

  comment-template:
    description: 'Custom comment template (supports placeholders: {deployment_url}, {deployment_status}, {worker_name}, {custom_message}, {comment_tag}, {pr_number})'
    required: false

  update-existing:
    description: 'Update existing comment instead of creating new one'
    required: false
    default: 'false'

  comment-tag:
    description: 'Unique tag for identifying comments to update'
    required: false
    default: 'cloudflare-workers-deployment'

outputs:
  comment-id:
    description: 'Posted comment ID'

  comment-url:
    description: 'Posted comment URL'

runs:
  using: 'node20'
  main: '../dist/comment/index.js'
