---
name: 'Cloudflare Workers PR Comment'
description: 'Post deployment information and preview URLs to PR comments'
author: 'harunonsystem'

branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  deployment-url:
    description: 'URL of the deployed preview'
    required: true

  deployment-status:
    description: 'Deployment status (success/failure)'
    required: false
    default: 'success'

  worker-name:
    description: 'Name of the deployed worker'
    required: false

  github-token:
    description: 'GitHub Token'
    required: true

  custom-message:
    description: 'Additional custom message'
    required: false

  comment-template:
    description: 'Custom comment template (markdown supported)'
    required: false

  update-existing:
    description: 'Update existing comment instead of creating new one'
    required: false
    default: 'true'

  comment-tag:
    description: 'Unique tag to identify comments for updates'
    required: false
    default: 'cloudflare-workers-deployment'

outputs:
  comment-id:
    description: 'ID of the created/updated comment'

  comment-url:
    description: 'URL of the comment'

runs:
  using: 'node20'
  main: '../dist/comment/index.js'
