name: 'Cloudflare Workers Preview Deploy (Complete)'
description: 'Deploy preview environment with wrangler.toml update and PR comment'
author: 'harunonsystem'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API Token'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true

  # Worker設定
  worker-name-prefix:
    description: 'Worker name prefix (e.g., "2048-game-preview")'
    required: true
    default: 'preview'
  worker-name-suffix:
    description: 'Worker name suffix strategy: pr-number, branch-name, custom'
    required: false
    default: 'pr-number'
  custom-worker-name:
    description: 'Custom worker name (used when suffix is "custom")'
    required: false

  # wrangler.toml設定
  wrangler-toml-path:
    description: 'Path to wrangler.toml'
    required: false
    default: 'wrangler.toml'
  environment-name:
    description: 'Environment name in wrangler.toml'
    required: false
    default: 'preview'

  # ブランチフィルター
  branch-patterns:
    description: 'Comma-separated branch patterns to deploy (e.g., "feature/*,bugfix/*")'
    required: false
    default: 'feature/*,bugfix/*,hotfix/*'
  exclude-branches:
    description: 'Comma-separated branches to exclude (e.g., "develop,staging")'
    required: false
    default: 'develop,staging,main'

  # デプロイオプション
  build-command:
    description: 'Build command before deploy'
    required: false
    default: 'npm run build'
  skip-build:
    description: 'Skip build step'
    required: false
    default: 'false'

  # コメント設定
  comment-enabled:
    description: 'Post comment to PR'
    required: false
    default: 'true'
  comment-template:
    description: 'Custom comment template (supports variables: {{url}}, {{worker_name}}, {{branch}})'
    required: false

  # GitHub Token
  github-token:
    description: 'GitHub token for PR comments'
    required: true
    default: ${{ github.token }}

outputs:
  worker-name:
    description: 'Deployed worker name'
    value: ${{ steps.deploy.outputs.worker-name }}
  worker-url:
    description: 'Deployed worker URL'
    value: ${{ steps.deploy.outputs.worker-url }}
  deployment-id:
    description: 'Cloudflare deployment ID'
    value: ${{ steps.deploy.outputs.deployment-id }}
  deployed:
    description: 'Whether deployment was executed (true/false)'
    value: ${{ steps.check-branch.outputs.should-deploy }}

runs:
  using: 'composite'
  steps:
    # ブランチチェック
    - name: Check branch eligibility
      id: check-branch
      shell: bash
      run: |
        BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        echo "Current branch: $BRANCH"

        # 除外ブランチチェック
        IFS=',' read -ra EXCLUDED <<< "${{ inputs.exclude-branches }}"
        for pattern in "${EXCLUDED[@]}"; do
          pattern=$(echo "$pattern" | xargs)
          if [[ "$BRANCH" == $pattern ]]; then
            echo "Branch '$BRANCH' is excluded"
            echo "should-deploy=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        done

        # パターンマッチチェック
        IFS=',' read -ra PATTERNS <<< "${{ inputs.branch-patterns }}"
        MATCHED=false
        for pattern in "${PATTERNS[@]}"; do
          pattern=$(echo "$pattern" | xargs)
          if [[ "$BRANCH" == $pattern ]]; then
            MATCHED=true
            break
          fi
        done

        if [[ "$MATCHED" == "true" ]]; then
          echo "Branch '$BRANCH' matches deployment criteria"
          echo "should-deploy=true" >> $GITHUB_OUTPUT
        else
          echo "Branch '$BRANCH' does not match any pattern"
          echo "should-deploy=false" >> $GITHUB_OUTPUT
        fi

    # Worker名決定
    - name: Determine worker name
      id: worker-name
      if: steps.check-branch.outputs.should-deploy == 'true'
      shell: bash
      run: |
        case "${{ inputs.worker-name-suffix }}" in
          pr-number)
            if [[ -z "${{ github.event.pull_request.number }}" ]]; then
              echo "Error: PR number not available"
              exit 1
            fi
            SUFFIX="${{ github.event.pull_request.number }}"
            ;;
          branch-name)
            BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
            # ブランチ名をサニタイズ (英数字とハイフンのみ)
            SUFFIX=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
            ;;
          custom)
            if [[ -z "${{ inputs.custom-worker-name }}" ]]; then
              echo "Error: custom-worker-name is required when suffix is 'custom'"
              exit 1
            fi
            SUFFIX="${{ inputs.custom-worker-name }}"
            ;;
          *)
            echo "Error: Invalid worker-name-suffix: ${{ inputs.worker-name-suffix }}"
            exit 1
            ;;
        esac

        WORKER_NAME="${{ inputs.worker-name-prefix }}-${SUFFIX}"
        echo "Worker name: $WORKER_NAME"
        echo "name=$WORKER_NAME" >> $GITHUB_OUTPUT

    # wrangler.tomlバックアップ
    - name: Backup wrangler.toml
      if: steps.check-branch.outputs.should-deploy == 'true'
      shell: bash
      run: |
        cp "${{ inputs.wrangler-toml-path }}" "${{ inputs.wrangler-toml-path }}.backup"

    # wrangler.toml更新
    - name: Update wrangler.toml
      if: steps.check-branch.outputs.should-deploy == 'true'
      shell: bash
      run: |
        WORKER_NAME="${{ steps.worker-name.outputs.name }}"
        ENV_NAME="${{ inputs.environment-name }}"
        TOML_PATH="${{ inputs.wrangler-toml-path }}"

        # 環境セクションの存在確認
        if grep -q "^\[env\.$ENV_NAME\]" "$TOML_PATH"; then
          # 既存環境のnameを更新
          sed -i "/^\[env\.$ENV_NAME\]/,/^\[/ s/^name = .*/name = \"$WORKER_NAME\"/" "$TOML_PATH"
        else
          # 新規環境セクション追加
          cat >> "$TOML_PATH" << EOF

        [env.$ENV_NAME]
        name = "$WORKER_NAME"
        EOF
        fi

        echo "Updated wrangler.toml:"
        cat "$TOML_PATH"

    # ビルド
    - name: Build
      if: steps.check-branch.outputs.should-deploy == 'true' && inputs.skip-build != 'true'
      shell: bash
      run: ${{ inputs.build-command }}

    # デプロイ
    - name: Deploy to Cloudflare
      id: deploy
      if: steps.check-branch.outputs.should-deploy == 'true'
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
      run: |
        # wranglerインストール確認
        if ! command -v wrangler &> /dev/null; then
          echo "Installing wrangler..."
          npm install -g wrangler
        fi

        # デプロイ実行
        OUTPUT=$(wrangler deploy --env ${{ inputs.environment-name }} 2>&1)
        echo "$OUTPUT"

        # URL抽出
        WORKER_URL=$(echo "$OUTPUT" | grep -oP 'https://[^\s]+\.workers\.dev' | head -1)

        if [[ -z "$WORKER_URL" ]]; then
          echo "Warning: Could not extract worker URL"
          WORKER_URL="https://${{ steps.worker-name.outputs.name }}.workers.dev"
        fi

        echo "worker-name=${{ steps.worker-name.outputs.name }}" >> $GITHUB_OUTPUT
        echo "worker-url=$WORKER_URL" >> $GITHUB_OUTPUT
        echo "deployment-id=$(date +%s)" >> $GITHUB_OUTPUT

    # wrangler.tomlリストア
    - name: Restore wrangler.toml
      if: always() && steps.check-branch.outputs.should-deploy == 'true'
      shell: bash
      run: |
        if [[ -f "${{ inputs.wrangler-toml-path }}.backup" ]]; then
          mv "${{ inputs.wrangler-toml-path }}.backup" "${{ inputs.wrangler-toml-path }}"
        fi

    # PRコメント投稿
    - name: Post PR comment
      if: |
        steps.check-branch.outputs.should-deploy == 'true' &&
        inputs.comment-enabled == 'true' &&
        github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const workerName = '${{ steps.deploy.outputs.worker-name }}';
          const workerUrl = '${{ steps.deploy.outputs.worker-url }}';
          const branch = context.payload.pull_request.head.ref;
          const success = '${{ job.status }}' === 'success';

          let template = `${{ inputs.comment-template }}`;

          if (!template) {
            // デフォルトテンプレート
            if (success) {
              template = `### ✅ Preview Environment Deployed

          **Worker Name**: \`${workerName}\`
          **Preview URL**: ${workerUrl}
          **Branch**: \`${branch}\`

          The preview environment has been successfully deployed!`;
            } else {
              template = `### ❌ Preview Deployment Failed

          **Branch**: \`${branch}\`

          Please check the workflow logs for details.`;
            }
          } else {
            // カスタムテンプレート変数置換
            template = template
              .replace(/\{\{url\}\}/g, workerUrl)
              .replace(/\{\{worker_name\}\}/g, workerName)
              .replace(/\{\{branch\}\}/g, branch);
          }

          // 既存コメント検索
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.data.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('Preview Environment')
          );

          if (botComment) {
            // 既存コメント更新
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: template
            });
          } else {
            // 新規コメント作成
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: template
            });
          }
