name: Preview Deploy (GitFlow Pattern)

on:
  push:
    branches:
      - staging
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    env:
      # Edit these for your project
      APP_NAME: myapp
      SUBDOMAIN: harunonsystem

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: harunonsystem/cloudflare-actions/deploy@v1
        with:
          # Workflow mode: auto (gitflow/githubflow detection), gitflow, or githubflow
          workflow-mode: 'auto'
          # Exclude branches from deployment (CSV or JSON array)
          exclude-branches: 'dependabot,renovate'
          # Release branch pattern for gitflow mode
          release-branch-pattern: 'release/'
          # Determine environment based on branch/event
          environment: |
            ${{ github.event_name == 'pull_request' && 'preview' ||
                (github.ref_name == 'staging' && 'staging') ||
                (github.ref_name == 'develop' && 'develop') ||
                'preview' }}
          # Worker name pattern - deploy action will automatically generate and patch wrangler.toml for previews
          worker-name-pattern: |
            ${{ github.event_name == 'pull_request' && format('{0}-pr-{1}', env.APP_NAME, github.event.pull_request.number) || 
                (github.ref_name == 'staging' && format('{0}-staging', env.APP_NAME)) ||
                (github.ref_name == 'develop' && format('{0}-develop', env.APP_NAME)) ||
                (startsWith(github.ref_name, 'feature/') && format('{0}-feature-{1}', env.APP_NAME, github.ref_name)) ||
                format('{0}-{1}', env.APP_NAME, github.ref_name) }}
          subdomain: ${{ env.SUBDOMAIN }}
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            {
              "DATABASE_URL": "${{ secrets.STG_DATABASE_URL }}",
              "API_KEY": "${{ secrets.STG_API_KEY }}"
            }

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: harunonsystem/cloudflare-actions/comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          worker-url: ${{ steps.deploy.outputs.worker-url }}
          worker-name: ${{ steps.deploy.outputs.worker-name }}
          deployment-success: ${{ steps.deploy.outputs.success }}
          deployment-error: ${{ steps.deploy.outputs.error-message || '' }}
