name: Production Deploy

on:
  push:
    branches:
      - main
      - master
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      # Edit these for your project
      APP_NAME: myapp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Workers (Production)
        id: deploy
        uses: harunonsystem/cloudflare-actions/deploy@v1
        with:
          # Workflow mode: githubflow for main/master deployment
          workflow-mode: 'githubflow'
          # Exclude maintenance branches
          exclude-branches: 'dependabot,renovate,maintenance'
          environment: production
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            {
              "DATABASE_URL": "${{ secrets.PROD_DATABASE_URL }}",
              "API_KEY": "${{ secrets.PROD_API_KEY }}"
            }
