name: Preview Deploy (Using GitHub Secrets)

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: harunonsystem/cloudflare-actions/deploy@v1
        with:
          environment: preview
          worker-name-pattern: 'my-app-pr-{pr_number}'
          subdomain: harunonsystem
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            {
              "API_KEY": "${{ secrets.STG_API_KEY }}"
            }

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: harunonsystem/cloudflare-actions/comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          worker-url: ${{ steps.deploy.outputs.worker-url }}
          worker-name: ${{ steps.deploy.outputs.worker-name }}
          deployment-success: ${{ steps.deploy.outputs.success }}
          deployment-error: ${{ steps.deploy.outputs.error-message || '' }}
