name: Preview Deployment (Using GitHub Secrets)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate Worker URL
        id: url-gen
        uses: harunonsystem/cloudflare-actions/url-generator@v1
        with:
          environment: 'preview'
          worker-name-pattern: 'myapp-pr-{pr_number}'
          subdomain: 'harunonsystem' 
          # myapp-pr-{pr_number}.harunonsystem.workers.dev

      - name: Deploy to Preview
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy -e preview
          secrets: |
            DATABASE_URL=${{ secrets.STG_DATABASE_URL }}
            API_KEY=${{ secrets.STG_API_KEY }}

      - name: Comment PR
        if: always()
        uses: harunonsystem/cloudflare-actions/comment@v1
        with:
          deployment-url: ${{ steps.url-gen.outputs.url }}
          deployment-status: ${{ steps.deploy.outcome == 'success' && 'success' || 'failure' }}
          worker-name: ${{ steps.url-gen.outputs.worker-name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
