---
name: 'Load Cloudflare Secrets from 1Password'
description: 'Load Cloudflare secrets from 1Password vault for GitHub Actions'
inputs:
  export-env:
    description: 'Export secrets as environment variables'
    required: false
    default: 'true'
outputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API Token loaded from 1Password'
    value: ${{ steps.op-load-secret.outputs.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare Account ID loaded from 1Password'
    value: ${{ steps.op-load-secret.outputs.CLOUDFLARE_ACCOUNT_ID }}
runs:
  using: 'composite'
  steps:
    - name: Load Cloudflare secrets from 1Password
      id: op-load-secret
      uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: op://harunonpj/CLOUDFLARE_ACCOUNT_ID/harunonpj
        CLOUDFLARE_API_TOKEN: op://harunonpj/CLOUDFLARE_API_TOKEN/harunonpj

    - name: Verify Cloudflare secrets loaded
      shell: bash
      run: |
        # Verify secrets are loaded without exposing values in logs
        if [ -z "${{ steps.op-load-secret.outputs.CLOUDFLARE_ACCOUNT_ID }}" ]; then
          echo "❌ CLOUDFLARE_ACCOUNT_ID not loaded from 1Password"
          exit 1
        fi
        if [ -z "${{ steps.op-load-secret.outputs.CLOUDFLARE_API_TOKEN }}" ]; then
          echo "❌ CLOUDFLARE_API_TOKEN not loaded from 1Password"
          exit 1
        fi
        echo "✅ All Cloudflare secrets loaded successfully from 1Password"

    - name: Export secrets as environment variables (optional)
      if: ${{ inputs.export-env == 'true' }}
      shell: bash
      run: |
        echo "Exporting Cloudflare secrets as environment variables"
        echo "CLOUDFLARE_ACCOUNT_ID=${{ steps.op-load-secret.outputs.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
        echo "CLOUDFLARE_API_TOKEN=${{ steps.op-load-secret.outputs.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
