---
name: 'CI Checks'
description: 'Run common CI checks: install dependencies, build, type check, lint, and test'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 10

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build TypeScript
      run: pnpm run build
      shell: bash

    - name: Run type checking
      run: pnpm run typecheck
      shell: bash

    - name: Run linter (Oxlint)
      run: pnpm run lint
      shell: bash

    - name: Run tests (Vitest)
      run: pnpm test
      shell: bash
