name: Preview Deployment (Using 1Password CLI)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secrets from 1Password
        id: load-secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_API_TOKEN: 'op://cloudflare/preview/cloudflare-api-token'
          CLOUDFLARE_ACCOUNT_ID: 'op://cloudflare/preview/cloudflare-account-id'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy and Comment on PR (Secure)
        uses: harunonsystem/cloudflare-actions/deploy@v1
        with:
          environment: 'preview'
          worker-name-pattern: 'secure-app-pr-{pr_number}'
          cloudflare-api-token: ${{ steps.load-secrets.outputs.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ steps.load-secrets.outputs.CLOUDFLARE_ACCOUNT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            {
              "DATABASE_URL": "preview-db-connection-string",
              "API_KEY": "preview-api-key-value"
            }
