name: Cleanup Workers (GitHub Flow)

# PR がクローズされたときに自動削除
on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cleanup PR worker
        id: cleanup
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          # PR #123 → myapp-pr-123 が削除される
          # worker-names で完全一致指定
          worker-names: 'myapp-pr-${{ github.event.pull_request.number }}'
          
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: 'false'
      
      - name: Log result
        run: |
          echo "✅ Deleted: ${{ steps.cleanup.outputs.deleted-count }} worker"
          echo "Worker: myapp-pr-${{ github.event.pull_request.number }}"
