name: Cleanup Workers (Using GitHub Secrets)

# PR が閉じるか、毎日スケジュール実行で古い Workers を削除
on:
  pull_request:
    types: [closed]
  schedule:
    # 毎日 2 AM UTC に実行
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  # === PR クローズ時に PR Worker を削除 ===
  cleanup-pr-worker:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Cleanup PR worker
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          # PR 番号を使って特定の Worker を削除
          # 例: PR #123 → myapp-pr-123 を削除
          worker-names: 'myapp-pr-${{ github.event.pull_request.number }}'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: 'false'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

  # === 定期スケジュール実行で古い Workers を削除 ===
  cleanup-old-workers:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
      - name: Cleanup old preview workers
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          # myapp-pr-* パターンにマッチする全ての Workers を削除
          worker-pattern: 'myapp-pr-*'
          
          # これらは削除から除外（保護）
          exclude: 'myapp,myapp-develop,myapp-staging,*-production'
          
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: 'false'
