name: 'Preview Environment Setup'
description: 'Setup preview environment configuration for Cloudflare Workers'
author: 'harunonsystem'

branding:
  icon: 'edit'
  color: 'purple'

inputs:
  wrangler-toml-path:
    description: 'Path to wrangler.toml'
    required: false
    default: 'wrangler.toml'

  environment-name:
    description: 'Environment name in wrangler.toml'
    required: true

  worker-name:
    description: 'Worker name to set'
    required: true

  create-backup:
    description: 'Create backup before modification'
    required: false
    default: 'true'

  update-vars:
    description: 'JSON object of environment variables to update (e.g., {"ENVIRONMENT": "preview"})'
    required: false

  update-routes:
    description: 'JSON array of routes to set (e.g., ["example.com/*"])'
    required: false

outputs:
  backup-path:
    description: 'Path to backup file (if created)'
    value: ${{ steps.setup.outputs.backup-path }}
  updated:
    description: 'Whether file was updated'
    value: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup preview environment
      id: setup
      shell: bash
      run: |
        # Make script executable
        chmod +x "${{ github.action_path }}/scripts/setup.sh"

        # Source the script to use its functions
        source "${{ github.action_path }}/scripts/setup.sh"

        # Run main function
        BACKUP_PATH=$(main \
          "${{ inputs.wrangler-toml-path }}" \
          "${{ inputs.environment-name }}" \
          "${{ inputs.worker-name }}" \
          "${{ inputs.create-backup }}" \
          "${{ inputs.update-vars }}" \
          "${{ inputs.update-routes }}")

        # Set output
        if [[ -n "$BACKUP_PATH" ]]; then
          echo "backup-path=$BACKUP_PATH" >> $GITHUB_OUTPUT
        fi

        echo "✅ Preview environment setup completed"
        echo ""
        echo "Updated wrangler.toml:"
        cat "${{ inputs.wrangler-toml-path }}"
