name: 'Preview Environment Setup'
description: 'Setup preview environment configuration for Cloudflare Workers'
author: 'harunonsystem'

branding:
  icon: 'edit'
  color: 'purple'

inputs:
  wrangler-toml-path:
    description: 'Path to wrangler.toml'
    required: false
    default: 'wrangler.toml'

  environment-name:
    description: 'Environment name in wrangler.toml'
    required: true

  worker-name:
    description: 'Worker name to set'
    required: true

  create-backup:
    description: 'Create backup before modification'
    required: false
    default: 'true'

  update-vars:
    description: 'JSON object of environment variables to update (e.g., {"ENVIRONMENT": "preview"})'
    required: false

  update-routes:
    description: 'JSON array of routes to set (e.g., ["example.com/*"])'
    required: false

outputs:
  backup-path:
    description: 'Path to backup file (if created)'

  updated:
    description: 'Whether file was updated'

runs:
  using: 'node20'
  main: '../dist/preview-setup/src/index.js'
