name: 'Preview Deployment'
description: 'Deploy preview environment to Cloudflare Workers'
author: 'harunonsystem'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API Token'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true

  # Worker設定
  worker-name-prefix:
    description: 'Worker name prefix (e.g., "2048-game-preview")'
    required: true
    default: 'preview'
  worker-name-suffix:
    description: 'Worker name suffix strategy: pr-number, branch-name, custom'
    required: false
    default: 'pr-number'
  custom-worker-name:
    description: 'Custom worker name (used when suffix is "custom")'
    required: false

  # wrangler.toml設定
  wrangler-toml-path:
    description: 'Path to wrangler.toml'
    required: false
    default: 'wrangler.toml'
  environment-name:
    description: 'Environment name in wrangler.toml'
    required: false
    default: 'preview'

  # ブランチフィルター
  branch-patterns:
    description: 'Comma-separated branch patterns to deploy (e.g., "feature/*,bugfix/*")'
    required: false
    default: 'feature/*,bugfix/*,hotfix/*'
  exclude-branches:
    description: 'Comma-separated branches to exclude (e.g., "develop,staging")'
    required: false
    default: 'develop,staging,main'

  # デプロイオプション
  build-command:
    description: 'Build command before deploy'
    required: false
    default: 'npm run build'
  skip-build:
    description: 'Skip build step'
    required: false
    default: 'false'

  # コメント設定
  comment-enabled:
    description: 'Post comment to PR'
    required: false
    default: 'true'
  comment-template:
    description: 'Custom comment template (supports variables: {{url}}, {{worker_name}}, {{branch}})'
    required: false

  # GitHub Token
  github-token:
    description: 'GitHub token for PR comments'
    required: true
    default: ${{ github.token }}

outputs:
  worker-name:
    description: 'Deployed worker name'

  worker-url:
    description: 'Deployed worker URL'

  deployment-id:
    description: 'Cloudflare deployment ID'

  deployed:
    description: 'Whether deployment was executed (true/false)'

runs:
  using: 'node20'
  main: '../dist/preview-deploy/index.js'
