name: Cleanup Workers (Git Flow)

# Delete PR Worker when PR is closed
# Workers for develop / staging branches are protected
on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup PR worker with protection
        id: cleanup
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          # Delete with pattern myapp-pr-*
          # e.g., myapp-pr-1, myapp-pr-2, myapp-pr-123 will be deleted
          worker-pattern: 'myapp-pr-*'

          # Exclusion settings: supports both exact match and wildcards
          # Will NOT be deleted:
          #   - myapp-dev, myapp-stg (exact match)
          #   - myapp-release-1, myapp-release-v1.0 (pattern)
          #   - api-prod, web-prod (pattern)
          #   - myapp (production environment)
          exclude: 'myapp-dev,myapp-stg,myapp-release-*,*-prod,myapp'

          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: 'false'

      - name: Log result
        run: |
          echo "✅ Cleanup completed"
          echo "Deleted: ${{ steps.cleanup.outputs.deleted-count }} worker(s)"
          if [ -n "${{ steps.cleanup.outputs.skipped-workers }}" ]; then
            echo "⚠️  Skipped: ${{ steps.cleanup.outputs.skipped-workers }}"
          fi
