---
name: Multi-Trigger Cleanup

# Production-ready cleanup with multiple triggers:
# 1. Auto-delete when PR is closed
# 2. Manual execution via workflow_dispatch
on:
  pull_request:
    types: [closed]

  workflow_dispatch:
    inputs:
      worker-names:
        description: 'Worker names to delete (comma separated)'
        required: false
        default: 'myapp-pr-1'
      worker-prefix:
        description: 'Worker prefix (e.g., "myapp-pr-")'
        required: false
      worker-numbers:
        description: 'Worker numbers to delete (e.g., "1,2,3")'
        required: false
      dry-run:
        description: 'Dry run mode (true=preview only, false=actual deletion)'
        required: false
        default: 'true'

permissions:
  contents: read

jobs:

  pr-cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Delete closed PR worker
        id: cleanup
        uses: harunonsystem/cf-workers-actions/cleanup@v1
        with:
          worker-names: 'myapp-pr-${{ github.event.pull_request.number }}'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: 'false'

      - name: Log result
        run: |
          echo "✅ Deleted worker: myapp-pr-${{ github.event.pull_request.number }}"

  manual-cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Cleanup workers
        id: cleanup
        uses: harunonsystem/cf-workers-actions/cleanup@v1
        with:
          worker-names: ${{ github.event.inputs.worker-names }}
          worker-prefix: ${{ github.event.inputs.worker-prefix }}
          worker-numbers: ${{ github.event.inputs.worker-numbers }}
          exclude: 'myapp,myapp-dev,myapp-stg,*-production,*-prod'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          dry-run: ${{ github.event.inputs.dry-run }}

      - name: Show results
        run: |
          echo "Names: ${{ github.event.inputs.worker-names }}"
          echo "Prefix: ${{ github.event.inputs.worker-prefix }}"
          echo "Numbers: ${{ github.event.inputs.worker-numbers }}"
          echo "Dry-run: ${{ github.event.inputs.dry-run }}"

          if [ "${{ github.event.inputs.dry-run }}" = "true" ]; then
            echo "⚠️ DRY-RUN MODE - No actual deletion"
            echo "Would delete: ${{ steps.dryrun.outputs.dry-run-results }}"
          else
            echo "✅ Deleted: ${{ steps.cleanup.outputs.deleted-count }} workers"
            echo "Workers: ${{ steps.cleanup.outputs.deleted-workers }}"
          fi
