name: Cleanup Workers (GitFlow)

on:
  pull_request:
    types: [closed]
  schedule:
    # Run cleanup weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup specific PR worker (on PR close)
        if: github.event_name == 'pull_request'
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-names: 'myapp-pr-${{ github.event.pull_request.number }}'
          exclude: 'myapp-develop,myapp-staging,myapp-main,myapp,*-production'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          confirm-deletion: 'yes'

      - name: Cleanup old PR workers (scheduled)
        if: github.event_name == 'schedule'
        uses: harunonsystem/cloudflare-actions/cleanup@v1
        with:
          worker-pattern: 'myapp-pr-*'
          exclude: 'myapp-develop,myapp-staging,myapp-main,myapp,*-production,myapp-pr-important-*'
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          confirm-deletion: 'yes'
